scope: Use FALSE instead of NULL for gboolean
Fixes warnings with clang 15+

scope/src/stack.c:168:11: error: incompatible pointer to integer conversion initializing 'gboolean' (aka 'int') with an expression of type 'void *' [-Wint-conversion]
        gboolean entry = NULL;
                 ^       ~~~~
1 error generated.

Signed-off-by: Khem Raj <raj.khem@gmail.com>