Fix cppcheck false-positive warning
Cppcheck warns about:
prjorg-menu.c:142: error: Uninitialized variable: elem
which is more or less a false-positive but the explicit
initialization won't hurt.